services:
  bank-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-migration
    container_name: marketplace-migration
    volumes:
      - /home/kinoko/logs/marketplace-migration:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33300:33300"

networks:
  backend:
    external: true
